# Generated by Django 4.2.6 on 2023-10-16 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionproductos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='analisis_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='analisis_leche/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
